# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
  contextPath: /angular-1-spring-boot-starter
  port: 8080 

management:
  context-path: /manage
#  security:
#    roles: 

spring:
  jta:
    enabled: false

  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      # valid values: none, validate, update, create, create-drop
      ddl-auto: none
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

  messages:
        basename: classpath:/i18n/messages
  mvc:
    favicon:
      enabled: false

endpoints:
  jmx:
    domain: spring.jmx.angular-1-spring-boot-starter


security:
  basic:
    enabled: false


# ===================================================================
# Application specific properties
# ===================================================================

com.michaelhoffmantech.angular-1-spring-boot-starter:
  async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
  #cors: #By default CORS are not enabled. Uncomment to enable.
    #allowed-origins: "*"
    #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    #allowed-headers: "*"
    #exposed-headers:
    #allow-credentials: true
    #max-age: 1800
  mail:
    from: test@localhost
  #security:
  #    authentication:
  #        oauth:
  #            clientid: sampleapp
  #            secret: mySecretOAuthSecret
  #            # Token is valid 30 minutes
  #            tokenValidityInSeconds: 1800
  #    rememberme:
  #        # security key (this key should be unique for your application, and kept secret)
  #        key: 
  swagger:
    title: Angular 1 Spring Boot Starter API
    description: Angular 1 Spring Boot Starter API documentation
    version: 1.0.0
    termsOfServiceUrl: "http://www.example.com/terms_of_service"
    contact: "Michael Hoffman Tech"
    license: "Michael Hoffman Tech"
    licenseUrl: "http://www.michaelhoffmaninc.com"

logging:
  file: angular-1-spring-boot-starter.log
